Revert "Merge pull request #1825 from tursodatabase/lucio/sync-switch-hyper"
This reverts commit 265bd83982f261e09bdc1b5c48153ed38fe93a6a, reversing
changes made to 909b8af8172cad079c1e0e08f877b22c056b1fd8 because it breaks the example app:

```
thread 'main' panicked at /Users/penberg/src/tursodatabase/libsql/libsql/src/local/database.rs:502:49:
called `Result::unwrap()` on an `Err` value: hyper::Error(Connect, "invalid URL, scheme is not http")
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```