Revert "Merge pull request #1791 from awakecoding/libsql-ffi-build-cp-fix"
This reverts commit 5ee4723699e3f79eca5ff7c2d6c0ed04c016711d, reversing
changes made to cc1d9c5afdfef2f913b0cf93a3ebaf96787c568e because it breaks `libsql-js` build on macOS:

```
penberg@vonneumann libsql-js % cargo check
    Updating git repository `https://github.com/tursodatabase/libsql/`
   Compiling libsql-ffi v0.5.0 (https://github.com/tursodatabase/libsql/?rev=9c73c68f0b034c5e01a51d9dc93a61936a71c801#9c73c68f)
   Compiling libsql-sqlite3-parser v0.13.0 (https://github.com/tursodatabase/libsql/?rev=9c73c68f0b034c5e01a51d9dc93a61936a71c801#9c73c68f)
    Checking reqwest v0.12.9
    Checking libsql-hrana v0.2.0 (https://github.com/tursodatabase/libsql/?rev=9c73c68f0b034c5e01a51d9dc93a61936a71c801#9c73c68f)
error: failed to run custom build command for `libsql-ffi v0.5.0 (https://github.com/tursodatabase/libsql/?rev=9c73c68f0b034c5e01a51d9dc93a61936a71c801#9c73c68f)`

Caused by:
  process didn't exit successfully: `/Users/penberg/src/tursodatabase/libsql-js/target/debug/build/libsql-ffi-755a07789947d931/build-script-build` (exit status: 101)
  --- stdout
  cargo:rustc-link-lib=framework=Security
  cargo:rerun-if-changed=bundled/src/sqlite3.c
  cargo:rerun-if-changed=/Users/penberg/src/tursodatabase/libsql-js/target/debug/build/libsql-ffi-e660048e9fb948a4/out/sqlite3mc/libsqlite3mc_static.a

  --- stderr
  cp: illegal option -- -
  usage: cp [-R [-H | -L | -P]] [-fi | -n] [-aclpSsvXx] source_file target_file
         cp [-R [-H | -L | -P]] [-fi | -n] [-aclpSsvXx] source_file ... target_directory
  thread 'main' panicked at /Users/penberg/.cargo/git/checkouts/libsql-311658d335deb3b1/9c73c68/libsql-ffi/build.rs:43:44:
  called `Result::unwrap()` on an `Err` value: Custom { kind: Other, error: "Failed to copy using cp" }
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
```