query_analysis: allow defer_foreign_keys pragma on primary
This pragma is useful for turning off foreign keys as a oneshot
operation within current transaction.

Example from turso shell:
```
→  create table t(id);
→  create table t2(id, v references t(id));
```
```
-- First insert to t2 fails, because t has no row with value (6)
→  pragma foreign_keys=on; begin; insert into t2 values(5,6); insert into t values (6); commit;
Error: SQLite error: FOREIGN KEY constraint failed
```
```
-- First insert doesn't fail, because checking foreign keys is deferred
-- until the transaction finishes
→  pragma foreign_keys=on; begin; pragma defer_foreign_keys=true; insert into t2 values(5,6); insert into t values (6); commit;
OK
```